server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: movie-service
          uri: lb://movie-service
          predicates:
            - Path=/movies/**
          ##filters:
            ##- StripPrefix=2
            ##- name: CircuitBreaker
              ##args:
                ##name: moviesService
                ##fallbackUri: forward:/fallback/movies
        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/catalog/**
          ##filters:
            ##- StripPrefix=2
            ##- name: CircuitBreaker
              ##args:
                ##name: catalogService
                ##fallbackUri: forward:/fallback/catalog
        - id: series-service
          uri: lb://series-service
          predicates:
            - Path=/series/**
          ##filters:
            ##- StripPrefix=2
            ##- name: CircuitBreaker
              ##args:
                ##name: moviesService
                ##fallbackUri: forward:/fallback/movies
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

##ESTO SE DESCOMENTA DESPUES
  ##security:
    ##oauth2:
      ##client:
        ##registration:
          ##github:
            ##client-id: 3d6a6fb80f8ac740be52 ESTO CAMBIAR
            ##client-secret: 6307e390352e8e3314da7ff4425d6324f6418a98 ESTO CAMBIAR
##ESTO SE DESCOMENTA DESPUES
##queue:
  ##movie:
    ##name: MovieQueue

##management:
  ##endpoints:
    ##web:
      ##exposure:
        ##include: info
  ##info:
    ##env:
      ##enabled: true
  ##endpoint:
    ##info:
      ##enabled: true

info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: API Gateway
  svc:
    intanceid: ${eureka.instance.instance-id}
    port: ${server.port}

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
