server:
  port: 8065

spring:
  data:
    mongodb: 
      uri: mongodb://catalog-db:27019/catalogoBack
  zipkin:
    base-url: http://zipkin:9411/
    enabled: true
  rabbitmq:
    username: guest
    password: guest
    port: 5672
    host: rabbitmq

queue:
  movie:
    name: movieQueue
  series:
    name: seriesQueue
  catalog:
    name: catalogQueue

eureka:
  client:
    service-url:
      defaultZone: http://registry-service:8761/eureka
 
resilience4j:
  circuitbreaker:
    instances:
      movie:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15000
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
        allowHealthIndicatorToFail: false
        automaticTransitionFromOpenToHalfOpenEnabled: true

      series:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15000
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
        allowHealthIndicatorToFail: false
        automaticTransitionFromOpenToHalfOpenEnabled: true

  retry:
    instances:
      movies:
        waitDuration: 1000
        maxAttempts: 3
        retryExceptions:
          - feign.FeignException$InternalServerError

      series:
        waitDuration: 1000
        maxAttempts: 3
        retryExceptions:
          - feign.FeignException$InternalServerError