server:
  port: 8065

spring:
  data:
    mongodb: 
      uri: mongodb://localhost:27017/catalogoBack
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672

queue:
  catalog:
    name: catalogQueue

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
 
##ESTO NO SE DE QUE ES
##management:
  ##endpoints:
    ##web:
      ##exposure:
        ##include: info
  ##info:
    ##env:
      ##enabled: true
  ##endpoint:
    ##info:
      ##enabled: true