server:
  port: 8097
  
spring:
  data:
    mongodb: 
      uri: mongodb://localhost:27017/movieBack

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


  
##ESTO SE DESCOMENTA DESPUES
  ##rabbitmq:
    ##username: guest
    ##password: guest
    ##host: localhost
    ##port: 5672

##queue:
  ##movie:
    ##name: MovieQueue

##ESTO NO SE QUE ES
##management:
  ##endpoints:
    ##web:
      ##exposure:
        ##include: info
  ##info:
    ##env:
      ##enabled: true
  #endpoint:
   #info:
      #enabled: true