server:
  port: 8097
  
spring:
  data:
    mongodb: 
      uri: mongodb://movie-db:27018/movieBack
  zipkin:
    base-url: http://zipkin:9411/
    enabled: true
  rabbitmq:
    username: guest
    password: guest
    host: rabbitmq
    port: 5672


queue:
  movie:
    name: movieQueue

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka
    fetch-registry: true
    register-with-eureka: true