server:
  port: 8098

spring:
  data:
    mongodb: 
      uri: mongodb://series-db:27017/serieBack
  zipkin:
    base-url: http://zipkin:9411/
    enabled: true
  rabbitmq:
    username: guest
    password: guest
    port: 5672
    host: rabbitmq

queue:
  series:
    name: serieQueue

eureka:
  client:
    service-url:
      defaultZone: http://registry-service:8761/eureka